### ISSUE TITLE
No funciona el experimento del método de Theis

### ISSUE THREAD

**Issue by fronate** [gthc-utpl/hydrovlab#7]
Al cargar el archivo de texto con los datos de abatimiento se producía un error.

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/120525501/207458119-30a9d57c-396f-4de7-b86e-a5b927359da1.png">

**Comment by lsantiago** [comment]
Se corrige el error creando la carpeta `c:\Tmp\HCANALES` en el servidor. La carpeta es necesaria para los archivos de entrada del experimento. 

![image](https://user-images.githubusercontent.com/37159/207460469-f4406eb2-e61e-4da9-8433-6b41ddfd0a87.png)
